export const PAYSLIP_LABELS = {
  MY_PAYSLIP: '我的薪資',
  NO_PAYSLIP_YET: '目前還沒有薪資單。會計確定當月薪資批次後、你會在這裡看到。',
  FINALIZED: '✓ 已確定',
  DRAFT: '⚠ 草稿（會計尚未確定）',
  NET_AMOUNT: '實領',
  INCOME: '收入',
  BASE_SALARY: '本薪',
  OVERTIME_PAY: '加班費',
  ATTENDANCE_BONUS: '全勤獎金',
  OTHER_ALLOWANCES: '其他津貼',
  GROSS_AMOUNT: '總收入',
  DEDUCTIONS: '扣款',
  LEAVE_DEDUCTION: '請假扣款',
  LABOR_INSURANCE: '勞保',
  HEALTH_INSURANCE: '健保',
  PENSION_VOLUNTARY: '自提勞退',
  INCOME_TAX: '所得稅',
  OTHER_DEDUCTIONS: '其他扣款',
  TOTAL_DEDUCTIONS: '總扣款',
  NET_PAY: '實領金額',
  WARNINGS: '注意事項',
  DETAILS: '明細',
} as const
