// 人資模組 UI 標籤常量

export const ATTENDANCE_PAGE_LABELS = {
  page_title: '出勤紀錄',
  breadcrumb_home: '首頁',
  breadcrumb_hr: '人資',
  breadcrumb_attendance: '出勤紀錄',
  placeholder_start_date: '開始日期',
  range_separator: '至',
  placeholder_end_date: '結束日期',
  all_employees: '全部員工',
  unknown_employee: '未知',
  col_date: '日期',
  col_employee: '員工',
  col_clock_in: '上班時間',
  col_clock_out: '下班時間',
  col_work_hours: '工時',
  col_overtime: '加班',
  col_status: '狀態',
  col_notes: '備註',
  action_edit: '編輯',
  action_delete: '刪除',
  summary_total_days: '總天數',
  summary_present: '正常',
  summary_late: '遲到',
  summary_absent: '缺勤',
  summary_total_hours: '總工時',
  summary_total_overtime: '總加班',
  empty_message: '尚無出勤紀錄',
  dialog_title_add: '新增出勤紀錄',
  dialog_title_edit: '編輯出勤紀錄',
  label_employee: '員工',
  label_date: '日期',
  label_clock_in: '上班時間',
  label_clock_out: '下班時間',
  label_status: '狀態',
  label_notes: '備註',
  placeholder_employee: '選擇員工',
  placeholder_date: '選擇日期',
  placeholder_notes: '備註說明',
  btn_cancel: '取消',
  btn_update: '更新',
  btn_add: '新增',
  confirm_delete_title: '刪除出勤紀錄',
  confirm_delete_message: (name: string | undefined, date: string) =>
    `確定要刪除 ${name} 於 ${date} 的出勤紀錄嗎？`,
  toast_deleted: '出勤紀錄已刪除',
  toast_updated: '出勤紀錄已更新',
  toast_created: '出勤紀錄已新增',
  error_required: '請選擇員工和日期',
}

export const PAYROLL_PAGE_LABELS = {
  page_title: '薪資管理',
  breadcrumb_home: '首頁',
  breadcrumb_hr: '人資',
  breadcrumb_payroll: '薪資管理',
  year_suffix: '年',
  month_suffix: '月',
  col_period: '期間',
  col_date_range: '日期範圍',
  col_status: '狀態',
  col_confirmed_at: '確認時間',
  btn_view: '查看',
  btn_calculate: '計算',
  btn_confirm: '確認',
  btn_mark_paid: '發放',
  empty_message: '尚無薪資期間',
  dialog_create_title: '建立薪資期間',
  label_year: '年度',
  label_month: '月份',
  btn_cancel: '取消',
  btn_create: '建立',
  toast_period_created: '薪資期間已建立',
  confirm_calculate_message: (year: number, month: number) =>
    `確定要計算 ${year}年${month}月 的薪資嗎？此操作會覆蓋現有的薪資紀錄。`,
  confirm_calculate_title: '計算薪資',
  toast_calculated: '薪資計算完成',
  confirm_confirm_message: (year: number, month: number) =>
    `確定要確認 ${year}年${month}月 的薪資嗎？確認後將無法修改。`,
  confirm_confirm_title: '確認薪資',
  toast_confirmed: '薪資已確認',
  confirm_paid_message: (year: number, month: number) =>
    `確定要標記 ${year}年${month}月 的薪資為已發放嗎？`,
  confirm_paid_title: '標記發放',
  toast_paid: '已標記為發放',
  records_dialog_title: (year: number, month: number) => `${year}年${month}月 薪資明細`,
  records_dialog_title_default: '薪資明細',
  summary_employees: '員工數',
  summary_gross: '應發總額',
  summary_net: '實發總額',
  summary_overtime: '加班費',
  summary_deductions: '扣款',
  empty_records: '尚無薪資紀錄，請先計算薪資',
  col_employee: '員工',
  col_base_salary: '底薪',
  col_overtime_pay: '加班費',
  col_bonus: '獎金',
  col_deductions_label: '扣款',
  col_gross: '應發',
  col_net: '實發',
  action_payslip: '薪資單',
  payslip_title: '薪資單',
  payslip_print_title: (name: string | undefined) => `薪資單 - ${name}`,
  payslip_employee_name: '員工姓名：',
  payslip_period: '薪資期間：',
  payslip_col_item: '項目',
  payslip_col_amount: '金額',
  payslip_base_salary: '底薪',
  payslip_overtime: (hours: string) => `加班費（${hours} 小時）`,
  payslip_bonus: '獎金',
  payslip_allowances: '津貼',
  payslip_other_additions: '其他加項',
  payslip_gross: '應發薪資',
  payslip_unpaid_leave: (days: number) => `無薪假扣款（${days} 天）`,
  payslip_other_deductions: '其他扣款',
  payslip_net: '實發薪資',
  payslip_work_days: (actual: number, total: number) => `出勤天數：${actual} / ${total} 天`,
  payslip_paid_leave: (days: number) => `有薪假天數：${days} 天`,
  payslip_unpaid_leave_days: (days: number) => `無薪假天數：${days} 天`,
  btn_print: '列印',
}

export const LEAVE_PAGE_LABELS = {
  page_title: '請假管理',
  breadcrumb_home: '首頁',
  breadcrumb_hr: '人資',
  breadcrumb_leave: '請假管理',
  tab_requests: '請假申請',
  tab_types: '假別設定',
  status_pending: '待審核',
  status_approved: '已核准',
  status_rejected: '已駁回',
  status_cancelled: '已取消',
  col_code: '代碼',
  col_type_name: '假別名稱',
  col_days_per_year: '年度配額',
  col_is_paid: '給薪',
  col_requires_proof: '需證明',
  col_is_active: '狀態',
  days_suffix: '天',
  days_unlimited: '無限制',
  yes: '是',
  no: '否',
  active: '啟用',
  inactive: '停用',
  action_edit: '編輯',
  action_delete: '刪除',
  col_employee: '員工',
  col_leave_type: '假別',
  col_start_date: '開始日期',
  col_end_date: '結束日期',
  col_days: '天數',
  col_status: '狀態',
  col_applied_at: '申請時間',
  btn_approve: '准',
  btn_reject: '駁',
  empty_requests: '尚無請假申請',
  init_hint: '尚未設定假別類型，建議初始化預設假別',
  btn_init: '初始化',
  confirm_init: '確定要初始化預設假別類型嗎？',
  confirm_init_title: '初始化假別',
  toast_initialized: '已成功初始化預設假別類型',
  confirm_delete_message: (name: string) => `確定要刪除「${name}」假別嗎？`,
  confirm_delete_title: '刪除假別',
  toast_type_deleted: '假別已刪除',
  confirm_approve_message: (
    name: string | undefined,
    type: string | undefined,
    start: string,
    end: string,
    days: number
  ) =>
    `確定要核准「${name}」的請假申請嗎？\n\n假別：${type}\n期間：${start} ~ ${end}\n天數：${days} 天`,
  confirm_approve_title: '核准請假',
  toast_approved: '已核准請假申請',
  reject_dialog_title: '駁回請假申請',
  reject_label: '駁回原因',
  reject_placeholder: '請輸入駁回原因...',
  error_reject_reason: '請填寫駁回原因',
  toast_rejected: '已駁回請假申請',
  btn_cancel: '取消',
  btn_reject_confirm: '確認駁回',
  type_section_title: '假別類型',
  dialog_title_add: '新增假別',
  dialog_title_edit: '編輯假別',
  label_type_name: '假別名稱',
  placeholder_type_name: '如：特休',
  label_code: '代碼',
  placeholder_code: '如：ANNUAL',
  label_days_per_year: '年度配額（天）',
  placeholder_days: '留空表示無限制',
  checkbox_paid: '給薪假',
  checkbox_proof: '需要證明文件',
  checkbox_active: '啟用',
  btn_update: '更新',
  btn_add: '新增',
  error_required: '請填寫假別名稱和代碼',
  toast_type_updated: '假別已更新',
  toast_type_created: '假別已新增',
}
// comp-hr 模組 UI 標籤常量

export const COMP_HR_LABELS = {
  加入頻道失敗_不影響員工建立: '⚠️ 加入頻道失敗（不影響員工建立）:',
  建立_Auth_帳號失敗: '⚠️ 建立 Auth 帳號失敗:',
  Auth_帳號已建立: '✅ Auth 帳號已建立:',
  一般: '一般',
  例_John: '例：John',
  例_王小明: '例：王小明',
  修改密碼: '修改密碼',
  儲存失敗_請稍後再試: '儲存失敗，請稍後再試',
  儲存失敗: '儲存失敗：',
  入職起薪: '入職起薪',
  再次輸入新密碼: '再次輸入新密碼',
  創建員工失敗_請稍後再試: '創建員工失敗，請稍後再試',
  取消: '取消',
  基本資料: '基本資料',
  密碼更新失敗_請稍後再試: '密碼更新失敗，請稍後再試',
  密碼更新失敗: '密碼更新失敗：',
  密碼長度至少需要8個字元: '密碼長度至少需要8個字元！',
  新密碼與確認密碼不符: '新密碼與確認密碼不符！',
  更新中: '更新中...',
  更新密碼: '更新密碼',
  未命名員工: '未命名員工',
  未設定: '未設定',
  權限: '權限',
  無法取得_workspace_請重新登入: '無法取得 workspace，請重新登入',
  系統主管: '系統主管',
  至少8個字元: '至少8個字元',
  薪資: '薪資',
  複製員工編號: '複製員工編號',
  複製密碼: '複製密碼',
  請填寫姓名: '請填寫姓名',
  請設定預設密碼: '請設定預設密碼',
  請選擇辦公室: '請選擇辦公室',
  跨空間: '跨空間',
  輸入備註: '輸入備註...',
  輸入職位: '輸入職位...',
  選擇日期: '選擇日期',
  選擇請款日期_週四: '選擇請款日期（週四）',

  LABEL_6686: '建立員工',

  LABEL_4383: '顯示名稱 *',
  LABEL_9768: '中文姓名',
  LABEL_3837: '英文姓名 *',
  GENERATING_9845: '員工編號（自動生成）',
  LABEL_3405: '身分證號',
  LABEL_8658: '生日',

  LABEL_2872: '職務資料',
  LABEL_9610: '入職日期',
  LABEL_8149: '起薪',

  LABEL_9167: '預設登入密碼',
  LABEL_3681: '員工可使用此密碼首次登入，建議提醒其登入後更改密碼',
  LABEL_4884: '員工角色（可複選）',
  PLEASE_SELECT_1794: '角色會影響員工可使用的功能。一般員工請選擇「一般員工」',

  LABEL_4950: '員工資料已成功建立，請記錄以下登入資訊',
  LABEL_7801: '已成功創建！',
  LABEL_4929: '員工編號',
  LABEL_LOGIN_EMAIL: '登入 Email',
  LABEL_9036: '預設密碼',
  LABEL_4950_1: '請提醒員工首次登入後更改密碼',
  LABEL_6771: '完成',

  LABEL_4949: '權限：',
  SAVE: '儲存',
  EDIT: '編輯',

  LABEL_5426: '薪資請款',
  LABEL_5237: '為員工建立薪資請款單',
  LABEL_6907: '請款資訊',
  LABEL_297: '特殊出帳',
  LABEL_8278: '備註（選填）',
  LABEL_6620: '本次金額：',

  LABEL_4197: '職位',

  MANAGE_7095: '密碼管理',
  LABEL_7220: '新密碼',
  CONFIRM_1474: '確認新密碼',
  LABEL_8429: '建議包含數字和字母',
  LABEL_2074: '員工下次登入時需要使用新密碼',

  LABEL_60: '個人資料',
  LABEL_9773: '顯示名稱',
  LABEL_739: '英文姓名',

  SAVING_4983: '儲存中...',
  SELECT_1620: '選擇職位角色',
  LABEL_9521: '可複選',
  MANAGE_5279: '員工可以同時擁有多個角色。例如：同一人可以兼業務和管理職務。',
  ADD_9036: '這些權限由角色自動配置，如需調整請變更角色或在下方新增額外權限',
  LABEL_7322: '所有權限',
  ADD_223: '進階：新增額外功能權限（選填）',
  LABEL_8504: '如需賦予該員工角色以外的特殊權限，可在此勾選。一般情況下不需要調整。',
  AUTO_SAVED: '✓ 已自動儲存',
  DEFAULT_TAG: '(預設)',
  PASSWORD_MATCH: '✓ 密碼確認一致',
  PASSWORD_MISMATCH: '✗ 密碼確認不一致',

  LABEL_PINYIN: '護照拼音',
  LABEL_AUTH_EMAIL: '登入 Email',
}
