export const DATABASE_LABELS = {
  PAGE_TITLE: '資料庫管理',
  BATCH_IMPORT: '批次匯入',
  STATS_TITLE: '資料庫統計',
  STATS_DESC: '管理報價系統的所有資料內容，確保資料一致性和準確性',
  TOTAL_ITEMS: '總項目數',
  COVERAGE: '覆蓋地區',
  LAST_UPDATED: '上次更新',
  ITEMS: '項目',
  ENTER_MANAGEMENT: '進入管理',
  QUICK_ACTIONS: '快速操作',
  MANAGE_REGIONS: '管理地區',
  MANAGE_REGIONS_DESC: '國家、區域、主要城市設定',
  ADD_RATES: '新增車資',
  ADD_RATES_DESC: '更新各國車資參考報價',
  ADD_ATTRACTIONS: '新增景點',
  ADD_ATTRACTIONS_DESC: '快速添加新的旅遊景點',

  // Module titles and descriptions
  MODULE_TRAVEL: '旅遊資料庫',
  MODULE_TRAVEL_DESC: '國家、區域、城市、景點統一管理',
  MODULE_TRANSPORT: '車資管理',
  MODULE_TRANSPORT_DESC: '管理各國車資參考報價',
  MODULE_SUPPLIERS: '供應商管理',
  MODULE_SUPPLIERS_DESC: '管理合作供應商和價格清單',
  MODULE_ASSETS: '公司資源管理',
  MODULE_ASSETS_DESC: '管理公司 Logo、大小章、插圖等資源',
  MODULE_ARCHIVE: '封存資料管理',
  MODULE_ARCHIVE_DESC: '管理已封存的旅遊團、行程表，可還原或永久刪除',
}
