// 簽證模組 UI 標籤常量

const VISA_PAGE_LABELS = {
  page_title: '簽證管理',
  breadcrumb_home: '首頁',
  breadcrumb_visas: '簽證管理',
  selected_count_suffix: '筆',
  selected_prefix: '已選',
  btn_submit: '送件',
  btn_pickup: '取件',
  btn_return: '歸還',
  btn_reject: '退件',
  btn_cancel: '取消',
  btn_view_info: '查看簽證資訊',
  btn_batch_pickup: '批次下件',
  btn_add_visa: '新增簽證',
  title_submit: '送件給代辦商',
  title_pickup: '取件完成',
  title_return: '登記證件歸還',
  title_reject: '標記為退件',
  toast_submitted: (count: number) => `已送出 ${count} 筆簽證`,
  toast_returned: '已登記證件歸還',
  toast_updated: '簽證已更新',
  toast_add_failed: '新增簽證失敗，請稍後再試',
  toast_order_created: (num: string) => `已建立訂單：${num}`,
  toast_batch_pickup_done: (count: number) => `已完成 ${count} 筆下件`,
  error_no_default_tour: (year: number) =>
    `請先在簽證頁面設定 ${year} 年預設簽證團，或在表單中選擇團號`,
}

const VISA_TAB_LABELS = {
  all: '全部',
  pending: '待送件',
  submitted: '已送件',
  collected: '已取件',
  rejected: '退件',
  returned: '已歸還',
}

export const VISA_LIST_LABELS = {
  col_applicant: '申請人',
  col_contact: '聯絡人',
  col_phone: '電話',
  col_visa: '簽證',
  col_urgent: '急件',
  col_status: '狀態',
  col_received: '收件',
  col_submitted: '送件',
  col_expected: '預計下件',
  col_vendor: '送件單位',
  col_returned: '歸還',
  col_fee: '代辦費',
  col_cost: '成本',
  urgent_yes: '是',
  urgent_no: '-',
  action_edit: '編輯',
  action_delete: '刪除',
  confirm_delete_title: '刪除簽證記錄',
  confirm_delete_message: '確定要刪除此簽證記錄嗎？',
  confirm_delete_detail: '此操作無法復原',
  confirm_delete_ok: '確認刪除',
  confirm_delete_cancel: '取消',
}

export const VISA_INFO_DIALOG_LABELS = {
  title: '簽證資訊總覽',
  btn_copy: '複製已選擇項目',
  copy_success: (count: number) => `已複製 ${count} 個項目`,
  copy_empty: '請先勾選要複製的項目',
  copy_failed: '複製失敗，請重試',
  col_method: '取貨方式／身份',
  col_adult: '成人',
  col_child: '兒童（未滿14歲）',
  tab_passport: '護照',
  tab_taiwan: '台胞證',
  tab_usa_esta: '美國 ESTA',
}

export const ADD_VISA_DIALOG_LABELS = {
  title_add: '新增簽證',
  title_edit: '編輯簽證',
  submit_add: '批次新增簽證',
  submit_edit: '儲存',
  label_tour: '選擇團號',
  placeholder_tour: '請輸入或選擇團號（例如：0810）',
  label_order: '選擇訂單',
  order_optional: '(選填，未選擇將自動建立)',
  placeholder_order_ready: '請選擇訂單或留空自動建立',
  placeholder_order_disabled: '請先選擇團號',
  new_order: '+ 新增訂單',
  label_contact: '聯絡人',
  placeholder_contact: '請輸入聯絡人',
  label_phone: '聯絡電話',
  placeholder_phone: '請輸入聯絡電話',
  th_applicant: '申請人',
  th_visa_type: '簽證類型',
  th_urgent: '急件',
  th_received_date: '收件日期',
  th_return_date: '回件日期',
  th_fee: '辦理費用',
  th_urgent_fee: '急件費用',
  th_total_fee: '應收費用',
  th_add_more: '追加辦理',
  placeholder_applicant: '申請人',
  placeholder_type: '類型',
  placeholder_received: '收件日期',
  placeholder_return: '回件日期',
  tooltip_add_same: '追加同一人的其他簽證',
  tooltip_delete: '刪除',
  btn_add_applicant: '+ 新增辦理人',
  // 簽證類型分組
  group_passport: '護照',
  group_taiwan: '台胞證',
  group_usa: '美國簽證',
  // 簽證類型選項
  type_passport_adult: '護照 成人',
  type_passport_child: '護照 兒童',
  type_passport_adult_lost: '護照 成人 遺失件',
  type_passport_child_lost: '護照 兒童 遺失件',
  type_taiwan: '台胞證',
  type_taiwan_lost: '台胞證 遺失件',
  type_taiwan_first: '台胞證 首辦',
  type_usa_esta: '美國 ESTA',
  // 編輯模式額外欄位
  label_status: '狀態',
  placeholder_status: '選擇狀態',
  status_pending: '待送件',
  status_submitted: '已送件',
  status_collected: '已取件',
  status_returned: '已歸還',
  status_rejected: '退件',
  label_vendor: '送件單位',
  placeholder_vendor: '輸入送件單位',
  label_cost: '成本',
  label_submit_date: '送件時間',
  label_doc_return: '證件歸還',
  label_pickup_date: '取件時間',
  label_notes: '備註',
  placeholder_notes: '輸入備註...',
  placeholder_date: '選擇日期',
}

export const BATCH_OPERATION_LABELS = {
  pickup_title: '批次取件',
  reject_title: '批次退件',
  selected_prefix: '已選擇',
  selected_suffix: '筆簽證',
  pickup_date: '取件日期',
  reject_date: '退件日期',
  placeholder_date: '選擇日期',
  btn_cancel: '取消',
  btn_confirm_pickup: '確認取件',
  btn_confirm_reject: '確認退件',
}

export const BATCH_PICKUP_DIALOG_LABELS = {
  title: '批次下件',
  subtitle_matching: '- 配對結果',
  desc_upload: '上傳護照照片，系統將自動辨識並配對待取件的簽證',
  desc_matching: '確認配對結果，未配對的項目可手動選擇對應的簽證',
  upload_hint: '點擊上傳',
  upload_drag: '或拖曳護照照片',
  upload_formats: '支援 JPG, PNG（可多選）',
  files_selected: (count: number) => `已選擇 ${count} 個檔案：`,
  pending_visas: (count: number) => `目前有 ${count} 筆待取件簽證`,
  btn_cancel: '取消',
  btn_processing: '辨識中...',
  btn_start_ocr: (count: number) => `開始辨識 (${count})`,
  btn_back: '返回上傳',
  btn_confirming: '處理中...',
  btn_confirm_pickup: (count: number) => `確認下件 (${count})`,
}

export const PICKUP_SUMMARY_LABELS = {
  pickup_date: '取件日期',
  placeholder_date: '選擇日期',
  pending_prefix: '目前有',
  pending_suffix: '筆待取件簽證',
}

export const PICKUP_LIST_LABELS = {
  alt_passport: '護照',
  no_name: '(無法辨識姓名)',
  passport_label: '護照:',
  auto_matched: '自動配對成功',
  manual_select: '請手動選擇',
  placeholder_select: '-- 選擇簽證 --',
  already_selected: '(已選)',
  update_customer: '同時更新顧客護照資訊',
  ocr_failed_prefix: '辨識失敗：',
  ocr_failed_default: '無法解析護照資訊',
}

export const RETURN_DIALOG_LABELS = {
  title: '證件歸還',
  submit_label: '確認歸還',
  return_date: '歸還日期',
  placeholder_date: '選擇日期',
  notes_label: '備註',
  notes_optional: '(選填)',
  notes_placeholder: '例如：寄送、自取...',
  visa_count: (count: number) => `共 ${count} 筆簽證`,
  note_prefix: '[證件歸還]',
}

export const SUBMIT_DIALOG_LABELS = {
  title: '送件',
  submit_label: '確認送件',
  label_date: '送件日期',
  label_vendor: '代辦商',
  placeholder_date: '選擇日期',
  placeholder_vendor: '輸入或選擇代辦商',
  cost_section: (count: number) => `成本設定（共 ${count} 筆）`,
  history_cost: '歷史成本:',
  new_cost_record: '新的成本記錄',
  placeholder_cost: '成本',
  total_cost: '總成本',
}

export const CUSTOMER_MATCH_LABELS = {
  title: '旅客資料比對',
  found_match: (count: number, name: string) =>
    `找到 ${count} 位同名「${name}」的客戶，請確認是否為同一人`,
  new_customer: (name: string) => `「${name}」為新客戶，是否要新增到 CRM？`,
  no_detail: '尚無詳細資料',
  btn_is_this: '是此人',
  not_any: '都不是，新增為新客戶',
  create_new: (name: string) => `建立「${name}」的新資料`,
  btn_add: '新增',
  new_customer_label: '此為新客戶，尚無資料',
  btn_add_to_crm: '新增到 CRM',
}

export const ADD_CUSTOMER_FORM_LABELS = {
  title: '新增旅客資料',
  desc: (name: string) => `填寫「${name}」的資料（所有欄位皆為選填）`,
  label_name: '姓名',
  label_phone: '電話',
  label_email: 'Email',
  label_national_id: '身分證字號',
  section_passport: '護照資訊',
  label_passport_number: '護照號碼',
  label_passport_name: '護照拼音',
  label_passport_expiry: '護照效期',
  label_birth_date: '出生日期',
  label_gender: '性別',
  label_notes: '備註',
  label_passport_scan: '護照掃描檔',
  gender_male: '男',
  gender_female: '女',
  placeholder_optional: '選填',
  placeholder_date: '選擇日期',
  alt_passport_scan: '護照掃描檔',
  tooltip_remove_image: '移除圖片',
  upload_hint: '點擊或拖曳上傳護照掃描檔',
  upload_formats: '支援 JPG、PNG 格式',
  upload_note: '上傳護照掃描檔後，未來可直接調用，不需重新掃描',
  btn_cancel: '取消',
  btn_save: '儲存',
}
