// ============================
// Re-export from canonical source: @/types/tour.types
// ============================

export type {
  FlightSegment,
  FlightInfo,
  Tour,
  Member,
  TourAddOn,
  ItineraryFeature,
  FocusCard,
  LeaderInfo,
  MeetingInfo,
  HotelInfo,
  DailyActivity,
  DailyMeals,
  DailyImage,
  DailyItineraryDay,
  PricingItem,
  PricingDetails,
  ItineraryVersionRecord,
  Itinerary,
  PriceTier,
  FAQ,
  TourStatus,
  ContractStatus,
  ContractTemplate,
  TourCategory,
  CreateTourData,
  UpdateTourData,
  TourFilter,
  TourListItem,
  TourStats,
} from '@/types/tour.types'
