export const TOURS_LABELS = {
  LABEL_7445: '快速報價單',
  ADD_1598: '新增快速報價單',
  LABEL_2903: '查看',
  DELETE: '刪除',
  LABEL_3885: '尚未建立',

  EDIT: '編輯',

  LABEL_4272: '團名',
  LABEL_6293: '訂單數',
  TOTAL_7262: '總收入',
  TOTAL_2585: '總成本',
  LABEL_6713: '毛利',
  SETTINGS_6548: '獎金設定',
  LABEL_6960: '業務獎金',
  TOTAL_6305: '獎金總計',
  LABEL_1342: '結案後將自動產生獎金請款單，狀態變更為「結案」。',
  CANCEL: '取消',
  CLOSING_TITLE_PREFIX: '結案 - ',
  UNIT_COUNT: ' 筆',
  OP_BONUS: 'OP 獎金',
  PRINTING: '生成中...',
  PRINT_REPORT: '列印報表',
  PROCESSING: '處理中...',
  CONFIRM_CLOSE: '確認結案',
  CONFIRM_CLOSE_WARNING: '確定要結案嗎？結案後將無法修改訂單和請款。',
  CONFIRM_DELETE_PREFIX: '確定要刪除「',
  CONFIRM_DELETE_SUFFIX: '」嗎？此操作無法復原。',
  ITINERARY_VERSION: '行程版本',
  QUICK_QUOTE_COMPARE_PREFIX: '為「',
  QUICK_QUOTE_COMPARE_SUFFIX: '」建立多份快速報價單比價',
  QUICK_QUOTE: '快速報價單',
  UNNAMED: '未命名',
  NOT_QUOTED: '尚未報價',
  LABEL_5100: '已收款',
  CONFIRM_7150: '待確認',
  TOTAL_2951: '總收款',
  LABEL_1728: '待收款',

  LOADING_9771: '載入中...',

  LABEL_116: '收款單號',
  DATE: '日期',
  AMOUNT: '金額',
  LABEL_1423: '合計',
  LABEL_7189: '無收款紀錄',
  LABEL_9671: '請款單號',
  LABEL_1552: '供應商',
  LABEL_4310: '無支出紀錄',
  SETTINGS_6822: '無獎金明細',
  TYPE: '類型',
  LABEL_2076: '員工',
  LABEL_8378: '獎金請款明細',
}
