import { COMP_WORKSPACE_LABELS } from '../constants/labels'
const DEFAULT_CHANNEL_NAME = COMP_WORKSPACE_LABELS.一般討論
export const BOT_CHANNEL_NAME = COMP_WORKSPACE_LABELS.機器人助手
export const LAST_CHANNEL_STORAGE_KEY = 'workspace_last_channel_id'

export const CHANNEL_SWITCH_DELAY = 150

const DIALOG_TYPES = {
  SHARE_QUOTE: 'shareQuote',
  SHARE_TOUR: 'shareTour',
  NEW_PAYMENT: 'newPayment',
  NEW_RECEIPT: 'newReceipt',
  NEW_TASK: 'newTask',
  SHARE_ADVANCE: 'shareAdvance',
  SHARE_ORDERS: 'shareOrders',
  CREATE_RECEIPT: 'createReceipt',
  CREATE_PAYMENT: 'createPayment',
  SETTINGS: 'settings',
} as const

export const ALERT_MESSAGES = {
  LOGIN_REQUIRED: COMP_WORKSPACE_LABELS.請先登入才能發送訊息,
  SEND_FAILED: COMP_WORKSPACE_LABELS.發送訊息失敗_請稍後再試,
  DELETE_CHANNEL_CONFIRM: COMP_WORKSPACE_LABELS.確定要刪除頻道嗎_此操作無法復原,
  CHANNEL_DELETED: COMP_WORKSPACE_LABELS.頻道已刪除,
  DELETE_FAILED: COMP_WORKSPACE_LABELS.刪除頻道失敗_請稍後再試,
  CHANNEL_NAME_REQUIRED: COMP_WORKSPACE_LABELS.頻道名稱不能為空,
  UPDATE_SUCCESS: COMP_WORKSPACE_LABELS.頻道設定已更新,
  UPDATE_FAILED: COMP_WORKSPACE_LABELS.更新頻道失敗_請稍後再試,
} as const

export const PLACEHOLDER_TEXT = {
  QUOTE_SEARCH: COMP_WORKSPACE_LABELS.輸入報價單編號搜尋,
  TOUR_SEARCH: COMP_WORKSPACE_LABELS.輸入團號搜尋,
  PAYMENT_ITEM: COMP_WORKSPACE_LABELS.輸入請款項目,
  PAYMENT_AMOUNT: COMP_WORKSPACE_LABELS.輸入請款金額,
  PAYMENT_REASON: COMP_WORKSPACE_LABELS.輸入請款原因,
  RECEIPT_ITEM: COMP_WORKSPACE_LABELS.輸入收款項目,
  RECEIPT_AMOUNT: COMP_WORKSPACE_LABELS.輸入收款金額_2,
  PAYER_NAME: COMP_WORKSPACE_LABELS.輸入付款人,
  TASK_TITLE: COMP_WORKSPACE_LABELS.輸入任務標題,
  TASK_DESCRIPTION: COMP_WORKSPACE_LABELS.輸入任務描述,
  ASSIGNEE_NAME: COMP_WORKSPACE_LABELS.輸入成員名稱,
  CHANNEL_NAME: COMP_WORKSPACE_LABELS.頻道名稱,
  CHANNEL_DESCRIPTION: COMP_WORKSPACE_LABELS.頻道描述_選填,
} as const
