export const LABELS = {
  ADD_TODO: '新增待辦事項',
  ADD_TODO_DESC: '建立新的待辦任務，設定優先級和截止日期',
  TASK_TITLE: '任務標題',
  URGENCY: '緊急度',
  DEADLINE: '期限',
  NO_ASSIGN: '不指派（個人任務）',
  PUBLIC_TO_COMPANY: '公開給全公司',

  LABEL_7239: '公開',
  LABEL_9553: '待辦事項',
  ADD_25: '快速新增... (Enter)',
  EDIT: '編輯',
  DELETE: '刪除',
  LABEL_3467: '輸入任務標題...',
  SELECT_5234: '選擇日期',
  LABEL_7694: '指派給（可選）',
  EDIT_8913: '其他同事可以查看此待辦，但只有你和共享者可以編輯',
  LABEL_1974: '建立任務',
  CANCEL: '取消',

  // 狀態篩選
  STATUS_ACTIVE: '未完成',
  STATUS_PENDING: '待辦',
  STATUS_IN_PROGRESS: '作業中',
  STATUS_COMPLETED: '已完成',
  STATUS_CANCELLED: '取消',
  STATUS_DONE: '完成',

  // 其他 UI
  SEARCH_PLACEHOLDER: '搜尋任務...',
  ADD_TASK: '新增任務',
  DELETE_TODO_TITLE: '刪除待辦事項',
  DELETE_CONFIRM_PREFIX: '確定要刪除待辦事項「',
  DELETE_CONFIRM_SUFFIX: '」嗎？',
  DELETE_IRREVERSIBLE: '此操作無法復原',
  CONFIRM_DELETE: '確認刪除',
  DELETE_FAILED: '刪除失敗，請稍後再試',

  // Card / Column actions
  ADD_CARD: '新增卡片',
  RENAME: '重命名',
  DELETE_COLUMN: '刪除欄位',
  DELETE_SUBTASK: '刪除子任務',
  REMOVE: '移除',
  REMOVE_SHARE: '移除共享',
  ADD_FAILED: '新增失敗，請稍後再試',
  PLEASE_LOGIN_FIRST: '請先登入',
  MARK_COMPLETE: '標記完成',
  UNMARK_COMPLETE: '取消完成',
  NOT_SET: '未設定',
  LOADING_EMPLOYEES: '載入員工資料中...',
  ENTER_TITLE: '請填寫任務標題',
  PRIORITY: '優先度',
  ASSIGNEE: '負責人',
  COLUMN_NAME: '欄位名稱',

  // 表格欄位
  COL_TITLE: '任務標題',
  COL_PRIORITY: '優先級',
  COL_STATUS: '狀態',
  COL_DEADLINE: '期限',
}
