// 生成星野集團飯店 INSERT SQL 指令
const fs = require('fs')
const path = require('path')

// 讀取資料
const hotels = JSON.parse(fs.readFileSync(path.join(__dirname, 'hoshinoya-complete.json'), 'utf8'))

// 跳脫字元
function escapeSql(str) {
  if (str === null || str === undefined) return 'NULL'
  return `'${String(str).replace(/'/g, "''")}'`
}

// 陣列轉成 PostgreSQL array 語法
function arrayToSql(arr) {
  if (!arr || !Array.isArray(arr)) return 'NULL'
  const escaped = arr.map(item => escapeSql(item)).join(', ')
  return `ARRAY[${escaped}]`
}

// 生成 VALUES
const valuesList = hotels.map(hotel => {
  const vals = [
    escapeSql(hotel.name),
    escapeSql(hotel.english_name),
    escapeSql(hotel.brand),
    escapeSql(hotel.country_id),
    escapeSql(hotel.region_id),
    escapeSql(hotel.city_id),
    escapeSql(hotel.category),
    hotel.star_rating,
    escapeSql(hotel.hotel_class),
    escapeSql(hotel.description),
    arrayToSql(hotel.highlights),
    escapeSql(hotel.price_range),
    arrayToSql(hotel.facilities),
    escapeSql(hotel.website),
    'true',
  ]
  return `  (${vals.join(', ')})`
})

const sqlContent = `-- 星野集團 ${hotels.length} 間飯店匯入 SQL
-- Generated by NOVA on 2026-04-06

INSERT INTO public.luxury_hotels (
  name, name_en, brand, country_id, region_id, city_id, category, 
  star_rating, hotel_class, description, highlights, price_range, 
  facilities, website, is_active
) VALUES 
${valuesList.join(',\n')};
`

fs.writeFileSync(path.join(__dirname, 'import-hoshinoya.sql'), sqlContent, 'utf8')
console.log(`SQL 檔案生成完成：${hotels.length} 間飯店`)
