export { AccountSettings } from './AccountSettings'
export { SystemSettings } from './SystemSettings'
export { OtherSettings } from './OtherSettings'
export { PermissionManagementSettings } from './PermissionManagementSettings'
export { WorkspaceSwitcher } from './WorkspaceSwitcher'
export { ModuleManagementSettings } from './ModuleManagementSettings'
export { DevToolsSettings } from './DevToolsSettings'
